### ISSUE TITLE
issue with mac

### ISSUE THREAD

**Issue by amitajoy** [boothen/Json-Eclipse-Plugin#10]
I am getting following error:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: binary,epp.package.jee.executable.cocoa.macosx.x86_64,4.5.1.20150917-1200
No repository found containing: binary,org.eclipse.platform.ide.executable.cocoa.macosx.x86_64,4.5.1.M20150904-0015

how to install it on eclipse mars on mac?

Thanks,
Amit

**Comment by msteiger** [comment]
It is searching for a bundle that is unrelated to this plugin, so I'm closing this. I hope you were able to resolve this problem.

**Comment by PoornimaSankarapu** [comment]
@amitajoy I am also facing the same error. Were you able find a solution for this?
