### ISSUE TITLE
Unable to use spaces for formatting

### ISSUE THREAD

**Issue by StephenLynx** [boothen/Json-Eclipse-Plugin#12]
I see some options on the formatter settings, but none to make it use spaces instead of tabs.

**Comment by msteiger** [comment]
The JSON plugin should use the (default) eclipse text editor settings.

Note that Java has it's own settings.

**Comment by StephenLynx** [comment]
Thanks, that worked.
Maybe a note about what defines the formatting would be a good addition.

**Comment by msteiger** [comment]
Done!
