### ISSUE TITLE
Formatter settings: possible to make use of space conditional ?

### ISSUE THREAD

**Issue by teckert** [boothen/Json-Eclipse-Plugin#13]
The formatter settings don't seem to allow a conditional use of space, e.g. to make a space show up after a colon for a key only if the corresponding value is neither an array nor an object.

For example, I would like to be able to configure the formatter to produce this layout
```
{
  "key1":
  {
    "key2": "value2"
  }
}
```
Note how there is a space between the colon following "key2" and before "value" but not after the colon following "key1" and the inner object. The newlines before and after the braces are intentional, so the formatter is configured accordingly as well - I also could not find an option for those to provide the "conditional space" behavior.

If I understand the possible settings correctly, they only allow for either a space after both colons or none at all. Is there a way to achieve this ? If not, please consider this as a request :-)

**Comment by msteiger** [comment]
Sorry for the delay. What about a more generic rule: "No space before newline" ? Would that achieve what you want?

**Comment by msteiger** [comment]
Closing due to lack of feedback,
