### ISSUE TITLE
Folding feature is not there for the plugin

### ISSUE THREAD

**Issue by manish33** [boothen/Json-Eclipse-Plugin#15]
For complex JSON objects, JSON folding is necessary. It is very difficult to read JSON without folding. please add this feature to the plugin. I'm attaching an image for best folding example.  collapse all is must for the folding
![json auto folding for complex objects](https://user-images.githubusercontent.com/11520775/37827210-8c296f42-2ebc-11e8-9e34-d1d3d4ca979d.PNG)

**Comment by msteiger** [comment]
Sorry, I don't get what you mean. You can look at the tree structure in the "Outline" view and folding should work in both the editor and in this view.

See: https://github.com/boothen/Json-Eclipse-Plugin/blob/master/images/2016-04-16_editor_and_quickoutline.png
