### ISSUE TITLE
Sync outline with editor

### ISSUE THREAD

**Issue by AsharLohmar** [boothen/Json-Eclipse-Plugin#16]
It would be nice if when you click a "node" in the Outline panel, the editor would move to it.
I have large JSON file as configuration files for some of our applications (several thousands of line) this feature would come in handy.

**Comment by msteiger** [comment]
Yes, I agree. It's kinda tricky to make this work and sync. with live changes in the text editor. It's on my TODO list, but probably not being worked on in the near future.

You can press **CTRL+O** to open the "Quick Outline". This should provide the functionality you search for.

**Comment by AsharLohmar** [comment]
There's no need to keep it in full sync, could also become heavy for the editor. Something like update outline on save and move editor focus on double click on outline element should/could be enough.

**Comment by msteiger** [comment]
Fixed in version 1.1.2
