### ISSUE TITLE
Completely not working on Eclipse Oxygen?

### ISSUE THREAD

**Issue by FireController1847** [boothen/Json-Eclipse-Plugin#19]
I may just be using it wrong, but when I install it it does not give me the option to use a "Json editor" for my .json files...

Sorry I'm not including very many details. This is truly why I am stumped too. It is not erroring (afaik, I am unsure how to check).

~ Installed via Eclipse Marketplace ~

**Comment by msteiger** [comment]
It does work with eclipse Oxygen in general. Maybe it was not installed correctly on your machine. You can check that by going to Help -> About eclipse -> Installation Details 

You should find "JSON Editor" in the list of "Installed Software" and 7 plugins in the "plugins" tab. Can you find them?

**Comment by FireController1847** [comment]
Alright, it turns out this was happening to _all my plugins_. [This answer](https://stackoverflow.com/questions/2697882/plugins-installed-on-eclipse-not-visible) on StackOverflow told me to run Eclipse using Administrator Privileges (why wasn't it????), and that fixes it after I reinstalled! Huzzah! Thanks for your help :)
