### ISSUE TITLE
Installed, but won't do anything

### ISSUE THREAD

**Issue by Zangdorx** [boothen/Json-Eclipse-Plugin#22]
Hello, I've installed the plugin on Eclipse for Java Developers (Photon) from the Eclipse Marketplace.
Then I've restarted Eclipse, but now my json files are still being opened with the Text Editor, and I can't find any JSON Editor anywhere by looking through the settings, thus I assume it wasn't installed correctly or something, yet the Marketplace lists it as installed. I don't understand what I did wrong. Is it compatible with Photon?

**Comment by Zangdorx** [comment]
It's listed in the "Installed Software" list. The plugin's version is 1.1.2, with version 4.7.1 of ANTLR.

**Comment by msteiger** [comment]
Hmm .. that's odd. I tried to reproduce it and it works fine for me. Can you please uninstall and try version 1.1.1 instead? It's available on the same update site and you can select if if you click the "Show older versions" checkbox in the "Install New Software" dialog.

**Comment by Zangdorx** [comment]
I got it to work. I tried installing it while running Eclipse as administrator, which worked. Thanks for the help!

**Comment by msteiger** [comment]
Great news!
