### ISSUE TITLE
JSON Editor Plugin cannot be installed to Eclipse 2018-12 (4-10.0)

### ISSUE THREAD

**Issue by de-jcup** [boothen/Json-Eclipse-Plugin#23]
Using Eclipse 2018-12 (4.10.0) I am no longer able to install the plugin by eclipse marketplace.

The reason is the missing entry of supported eclipse version (4.10 is missing, 4.9 and 4.11 are listed) - see next picture from https://marketplace.eclipse.org/content/json-editor-plugin?mpc=true&mpc_state=#group-details

Could you please enable the checkbox entry for 4.10 in marketplace listing? I missing the plugin on my new eclipse installation...

Best wishes
Albert

![image](https://user-images.githubusercontent.com/11644753/51568245-89120580-1e99-11e9-9d38-0d28866a58aa.png)

**Comment by msteiger** [comment]
Thanks for reporting! The eclipse marketplace usually does this automatically, but it seems to not have worked this time. I selected it manually, so it should appear now. Can you please verify?

**Comment by de-jcup** [comment]
I just installed it from eclipse marketplace.
Works out of the box.

Thank you. :+1: 

Remark:
Maybe the problem was that you have already set 4.11 as being supported (which is not latest but development) and auto script does ignore older (latest) in this case ?
