### ISSUE TITLE
Couldn't get it to work with Eclipse PDT

### ISSUE THREAD

**Issue by timhj** [boothen/Json-Eclipse-Plugin#25]
Looks like a great editor add-on for Eclipse but it just would register as an editor after installation with PDT. Zend Eclipse PDT is a packaged version of Eclipse 3.8 so should work?

Tried installing via marketplace and direct from http://boothen.github.io/Json-Eclipse-Plugin/. Both times it looked like the install finished but json files stay as text in the project explorer editor and there's no mention of the JSON Editor anywhere in preferences or the list of internal editors for files.

**Comment by msteiger** [comment]
Are you sure it's eclipse 3.8? This version is really old (2011 or 2012 maybe) and was hardly ever used, since 4.0 was released almost simultaneously. 

I remember testing 3.7 for quite a while and it always worked OK, so I guess it would still work. Version 1.1.2 was compiled with Java 7, so this could be an issue. Do you find anything in the eclipse logs? You can find them in a View "Error Log"

**Comment by timhj** [comment]
Yup definitely 3.8 (well 3.8.1):
![screen shot 2019-02-06 at 10 29 10 am](https://user-images.githubusercontent.com/3896211/52311148-23c22680-29fa-11e9-9c31-bb5106f38959.png)

Here's what's in the logs from a fresh install this morning: 

`!ENTRY org.eclipse.ui 2 2 2019-02-06 10:31:06.730
!MESSAGE Invalid property category path: ValidationPropertiesPage (bundle: org.eclipse.wst.html.ui, propertyPage: org.eclipse.wst.html.ui.propertyPage.project.validation)

!ENTRY org.eclipse.ui 2 2 2019-02-06 10:31:06.731
!MESSAGE Invalid property category path: ValidationPropertiesPage (bundle: org.eclipse.wst.xml.ui, propertyPage: org.eclipse.wst.xml.ui.propertyPage.project.validation)
!SESSION 2019-02-06 10:31:08.994 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_65
java.vendor=Apple Inc.
BootLoader constants: OS=macosx, ARCH=x86, WS=cocoa, NL=en_US
Framework arguments:  -showlocation -keyring /Users/tim/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86 -showlocation -keyring /Users/tim/.eclipse_keyring -showlocation

!ENTRY org.eclipse.ui 2 0 2019-02-06 10:31:11.783
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2019-02-06 10:31:11.783
!MESSAGE Commands should really have a category: plug-in='org.eclipse.php.ui', id='org.eclipse.dltk.ui.edit.text.java.source.quickMenu', categoryId='org.eclipse.jdt.ui.category.source'

!ENTRY org.eclipse.core.net 1 0 2019-02-06 10:31:15.519
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.zend.php.zendserver.deployment.ui 4 0 2019-02-06 10:31:26.160
!MESSAGE Address already in use
!STACK 0
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:521)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:414)
	at java.net.ServerSocket.bind(ServerSocket.java:326)
	at java.net.ServerSocket.<init>(ServerSocket.java:192)
	at java.net.ServerSocket.<init>(ServerSocket.java:104)
	at org.zend.php.zendserver.deployment.ui.chrome.SocketCommandListener.openServerSocket(SocketCommandListener.java:69)
	at org.zend.php.zendserver.deployment.ui.chrome.SocketCommandListener$1.run(SocketCommandListener.java:39)
	at java.lang.Thread.run(Thread.java:695)
`

**Comment by msteiger** [comment]
Sorry for the delayed answer. All of the error messages seem to be unrelated unfortunately. Could you please try to install an older version from the update site?

Version 1.0.0 was compiled with Java6 and should work for you. If that solves your problem, we can think of ways to fix the issue for latest versions.

**Comment by msteiger** [comment]
Closing due to lack of feedback.
