### ISSUE TITLE
Add Package export to com.boothen.jsonedit.editor

### ISSUE THREAD

**Issue by sorontur** [boothen/Json-Eclipse-Plugin#28]
Hi,

I like to use your editor in a RCP project. Therefore i need to wrap it in my world. Currently that is not possible because the package where the JsonTextEditor class is located is not exported. Could you add such an export? That would be very great.

Kind Regards,
Patrick

**Comment by msteiger** [comment]
Sure, sounds reasonable. Can you make a PR for it?

**Comment by sorontur** [comment]
yes that would be great so that we can include it in our target platform.

**Comment by msteiger** [comment]
Version 1.1.3 is available now, @sorontur can you please test?
