### ISSUE TITLE
Random Block Selection

### ISSUE THREAD

**Issue by JustSpiffy** [boothen/Json-Eclipse-Plugin#5]
While typing, the plugin randomly selects a block of json and overwrites the block. This renders the plugin unusable.

My environment is:
  Ubuntu 14.04
  Eclipse Luna

Seems to be related to the outline, if I close the outline the selection stops.

**Comment by msteiger** [comment]
Thanks for reporting. You don't happen to be able to try on a Windows machine?

I'm thinking about disabling the block selection feature entirely, since it seems to happen for other users as well.

I don't get the bug on my Windows machine (or I'm doing it wrong).

**Comment by JustSpiffy** [comment]
I would suggest adding a simple check box in the options menu for now, some people may find the block selection useful, then revisiting when you have time to fix. (Maybe have it default to off)

Apologies, I do not have access to a Window machine.

**Comment by jeremiahbunton** [comment]
I am also having this issue, whenever I edit the file in any way it either highlights the line I am working on or the block.  Is there any way to turn this off?

**Comment by Noks2808** [comment]
Facing the same random block selection on an Ubuntu machine. Fixing this would make it very smooth.

**Comment by JustSpiffy** [comment]
The only way I found to disable block selection was by closing the outline window in Eclipse. (the one with the blue square icon).

**Comment by jeremiahbunton** [comment]
@JustSpiffy that does not work for me, I am on a mac.

@Noks2808 I agree without this feature this would be such an awesome tool.

**Comment by msteiger** [comment]
Thank you for your feedback. I'll try to free some time so I can investigate this. Probably only at around Christmas.

**Comment by YetAnotherCodeMonkey** [comment]
@JustSpiffy SO HELPFUL. It seems like every time the Outline is updated it changes the selection in the document. Closing the outline fixes it, thanks for the tip it was driving me nuts!

**Comment by msteiger** [comment]
Should be fixed in version 1.0.1 now - can you confirm this?

**Comment by jeremiahbunton** [comment]
@msteiger thank you very much it works great.
