### ISSUE TITLE
How to use Detects duplicate keys feature?

### ISSUE THREAD

**Issue by jasmines** [boothen/Json-Eclipse-Plugin#7]
I've installed json editor as eclipse plugin in aptana studio, but the feature in subject is not working.
How can I configure it?
How can I test it's working?

**Comment by msteiger** [comment]
You should be able to open a file as a JSON document. It should have the JSON icon and an outline page, etc. Then you should also see warnings in the "Problems" view for duplicate keys along with a list of syntax errors (if they exist). No configuration needed.
