### ISSUE TITLE
The icons for jsonedit-outline are barely visible on a dark theme

### ISSUE THREAD

**Issue by pedronavf** [boothen/Json-Eclipse-Plugin#8]
The icons for the JSON data type (Array, Boolean, etc) in the Outline view are dark blue, so they are very hard to see when using a Dark Theme (as shown in the screenshot below).

Ideally there would be two set of icons the user can choose from (those for the dark theme would be white) or the data type symbols would be plain text with an user selectable color in the preferences window.

![eclipse](https://cloud.githubusercontent.com/assets/1152016/22947248/2a147eae-f2af-11e6-8211-7533f92f25e9.png)

**Comment by msteiger** [comment]
Thanks for your feedback, Pedro. How about making the icons a bit brighter so they can be seen properly on both bright and dark backgrounds?

**Comment by pedronavf** [comment]
That sounds like a reasonable option, yes!

**Comment by msteiger** [comment]
Sorry for the delay. It would be great if you could provide (brighter) icons that work for you ...

**Comment by msteiger** [comment]
Can somebody please try it out?
